### ISSUE TITLE
Compilation fails on 7.5 compute capability?

### ISSUE THREAD

**Issue by cciccole** [CannyLab/tsne-cuda#54]
When I try to compile for a 7.5 compute capability with CUDA 10.0 or 10.1 I get errors about `Unknown __CUDA_ARCH__`

Here is a big dump showing context:

<details>

```
make[2]: *** [CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/tsnecuda_generated_L2Select.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building NVCC (Device) object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/tsnecuda_generated_IVFUtilsSelect1.cu.o
In file included from /app/third_party/faiss/gpu/impl/L2Norm.cu:13:0:
/app/third_party/faiss/gpu/impl/../utils/DeviceDefs.cuh:18:2: error: #error Unknown __CUDA_ARCH__; please define parameters for compute capability
 #error Unknown __CUDA_ARCH__; please define parameters for compute capability
  ^
CMake Error at tsnecuda_generated_L2Norm.cu.o.cmake:203 (message):
  Error generating
  /app/build/CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/./tsnecuda_generated_L2Norm.cu.o


make[2]: *** [CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/tsnecuda_generated_L2Norm.cu.o] Error 1
In file included from /app/third_party/faiss/gpu/impl/L2Norm.cu:13:0:
/app/third_party/faiss/gpu/impl/../utils/DeviceDefs.cuh:18:2: error: #error Unknown __CUDA_ARCH__; please define parameters for compute capability
 #error Unknown __CUDA_ARCH__; please define parameters for compute capability
  ^
CMake Error at tsnecuda_generated_L2Norm.cu.o.cmake:203 (message):
  Error generating
  /app/build/CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/./tsnecuda_generated_L2Norm.cu.o


make[2]: *** [CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/tsnecuda_generated_L2Norm.cu.o] Error 1
In file included from /app/third_party/faiss/gpu/impl/PQCodeDistances.cu:15:0:
/app/third_party/faiss/gpu/impl/../utils/DeviceDefs.cuh:18:2: error: #error Unknown __CUDA_ARCH__; please define parameters for compute capability
 #error Unknown __CUDA_ARCH__; please define parameters for compute capability
  ^
CMake Error at tsnecuda_generated_PQCodeDistances.cu.o.cmake:203 (message):
  Error generating
  /app/build/CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/./tsnecuda_generated_PQCodeDistances.cu.o


make[2]: *** [CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/tsnecuda_generated_PQCodeDistances.cu.o] Error 1
[ 26%] Linking CXX executable stl_logging_unittest
[ 26%] Built target stl_logging_unittest
In file included from /app/third_party/faiss/gpu/impl/PQCodeDistances.cu:15:0:
/app/third_party/faiss/gpu/impl/../utils/DeviceDefs.cuh:18:2: error: #error Unknown __CUDA_ARCH__; please define parameters for compute capability
 #error Unknown __CUDA_ARCH__; please define parameters for compute capability
  ^
CMake Error at tsnecuda_generated_PQCodeDistances.cu.o.cmake:203 (message):
  Error generating
  /app/build/CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/./tsnecuda_generated_PQCodeDistances.cu.o


make[2]: *** [CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/tsnecuda_generated_PQCodeDistances.cu.o] Error 1
[ 26%] Linking CXX static library ../../../lib/libgmock.a
[ 26%] Built target gmock
Scanning dependencies of target gmock_main
In file included from /app/third_party/faiss/gpu/impl/../utils/WarpShuffles.cuh:13:0,
                 from /app/third_party/faiss/gpu/impl/../utils/Pair.cuh:14,
                 from /app/third_party/faiss/gpu/impl/../utils/Limits.cuh:13,
                 from /app/third_party/faiss/gpu/impl/Distance.cu:17:
/app/third_party/faiss/gpu/impl/../utils/DeviceDefs.cuh:18:2: error: #error Unknown __CUDA_ARCH__; please define parameters for compute capability
 #error Unknown __CUDA_ARCH__; please define parameters for compute capability
  ^
[ 27%] Building CXX object third_party/gtest/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
In file included from /app/third_party/faiss/gpu/impl/IVFFlatScan.cu:14:0:
/app/third_party/faiss/gpu/impl/../utils/DeviceDefs.cuh:18:2: error: #error Unknown __CUDA_ARCH__; please define parameters for compute capability
 #error Unknown __CUDA_ARCH__; please define parameters for compute capability
  ^
CMake Error at tsnecuda_generated_IVFFlatScan.cu.o.cmake:203 (message):
  Error generating
  /app/build/CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/./tsnecuda_generated_IVFFlatScan.cu.o


make[2]: *** [CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/tsnecuda_generated_IVFFlatScan.cu.o] Error 1
CMake Error at tsnecuda_generated_Distance.cu.o.cmake:203 (message):
  Error generating
  /app/build/CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/./tsnecuda_generated_Distance.cu.o


make[2]: *** [CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/tsnecuda_generated_Distance.cu.o] Error 1
In file included from /app/third_party/faiss/gpu/impl/../utils/WarpShuffles.cuh:13:0,
                 from /app/third_party/faiss/gpu/impl/../utils/Pair.cuh:14,
                 from /app/third_party/faiss/gpu/impl/../utils/Limits.cuh:13,
                 from /app/third_party/faiss/gpu/impl/Distance.cu:17:
/app/third_party/faiss/gpu/impl/../utils/DeviceDefs.cuh:18:2: error: #error Unknown __CUDA_ARCH__; please define parameters for compute capability
 #error Unknown __CUDA_ARCH__; please define parameters for compute capability
```

</details>

I tried adding these lines in the `CMakelists.txt` file:
```
                    -gencode=arch=compute_75,code=sm_75
                    -gencode=arch=compute_75,code=compute_75
```
I tried both of them by themselves as well as together.

Are you all able to compile for this architecture? Maybe it's just something about my env or some other arg that isn't correct?

**Comment by DavidMChan** [comment]
The issue is that we rely on a custom fork of FAISS (https://github.com/DavidMChan/faiss) which hasn't been merged with the latest upstream - so we don't yet have 7.5 support. Compiling with 7.0 should still work with the latest Turing GPUs until we get everything merged.

**Comment by cciccole** [comment]
Maybe I'm missing some nuance here but compiling with 7.0 doesn't allow me to use the nvidia T4. Thoughts?

Sounds like a reasonably clear path forward for 7.5 support unless there are a lot of changes to reconcile? Any thoughts on when that will be worked on?

**Comment by DavidMChan** [comment]
What is the error that you're getting by running 7.0 on the T4? Compiling with 7.0 works fine on our Titan RTX machines which are also on the Turing architecture. 

There's probably a clear path forward, however it's unclear how many changes will have to be made to update the FAISS version.

**Comment by cciccole** [comment]
Okay so I realized my previously mentioned run attempt was compiled with arch 7.0 on CUDA 9. That is what cannot run on the T4. Does that seem correct? The error was:

<details>

```
>>> tsnecuda.test()
Initializing cuda handles... done.
KNN Computation... done.
Computing Pij matrix... CUBLAS error in file '/app/src/util/cuda_utils.cu', line 101, error: CUBLAS_STATUS_EXECUTION_FAILED
terminating!
python: /app/src/util/cuda_utils.cu:103: void __CublasSafeCall(cublasStatus_t, const char*, int): Assertion `0' failed.
Aborted (core dumped)
```

</details>

I went back to compile with arch 7.0 on CUDA 10 and 10.1 in case that matters. Now I'm getting different compilation error(s) that I believe I have accurately captured below:
<details>

```
/app/third_party/faiss/gpu/utils/DeviceUtils.cpp: In function 'int faiss::gpu::getDeviceForAddress(const void*)':
/app/third_party/faiss/gpu/utils/DeviceUtils.cpp:98:18: warning: 'cudaPointerAttributes::memoryType' is deprecated (declared at /usr/local/cuda/include/driver_types
.h:1189) [-Wdeprecated-declarations]
   } else if (att.memoryType == cudaMemoryTypeHost) {
                  ^
/app/third_party/faiss/gpu/utils/DeviceUtils.cpp:98:18: warning: 'cudaPointerAttributes::memoryType' is deprecated (declared at /usr/local/cuda/include/driver_types
.h:1189) [-Wdeprecated-declarations]
[ 74%] Linking CXX executable tsne
lib/libfaiss.so: undefined reference to `dsyev_'
lib/libfaiss.so: undefined reference to `sgeqrf_'
lib/libfaiss.so: undefined reference to `sorgqr_'
lib/libfaiss.so: undefined reference to `sgesvd_'
collect2: error: ld returned 1 exit status
make[2]: *** [tsne] Error 1
make[1]: *** [CMakeFiles/tsne.dir/all] Error 2
make: *** [all] Error 2
```
</details>

So now a problem is that I can't compile for arch 7.0 with CUDA 10.

It should be noted that I'm compiling inside a container based on nvidia's docker image nvidia/cuda:10.1-devel-ubuntu14.04. I'm using this image because it does not list `nvidia-docker v2` as a dependency as I don't want to deal with that package. However, the image I'm using could be poorly labeled and maybe my issue stems from the quasi-support for CUDA 10 with docker.

Let me know if you have any ideas, but don't go out of your way if this seems like an unknown environment issue. My sooner request would be a newly built conda package for the current master so I can see if I can run on a T4 without having to compile for it.

**Comment by DavidMChan** [comment]
We added a new conda build, which you should be able to try to use on the new architectures - if this doesn't work, I'll take a closer look.
